modName=ItemBlacklist
modId=ItemBlacklist
modGroup=net.doubledoordev.itemblacklist
modVersion=1.2.0
archiveBaseName=ItemBlacklistUnfucked

minecraftVersion=1.7.10
forgeVersion=10.13.4.1614
channel=stable
mappingsVersion=12

javaVersion=8

gtnh.settings.blowdryerTag=0.2.2
gtnh.modules.codeStyle=false
autoUpdateBuildScript=false
includeWellKnownRepositories=true

enableModernJavaSyntax=false
enableGenericInjection=true

usesMixins=false
usesShadowedDependencies=false
usesMavenPublishing=false

accessTransformersFile=
coreModClass=core.ItemBlacklistLoadingPlugin
apiPackage=
mixinPlugin=
mixinConfig=

org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
